---
abstract: 'Count interval statistics in realtime'
author:
  - 'Viktor Turskyi <koorchik@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-OnlineCounter
provides:
  Statistics::OnlineCounter:
    file: lib/Statistics/OnlineCounter.pm
    version: 0.01
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 0.01
